language: node_js
node_js:
- '0.10'
before_install:
- sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
- git submodule update --init --recursive
- npm install -g grunt-cli
install:
- npm install
- grunt pack --no-color
script:
- npm test
after_success:
- export RFILENAME=`date +%m%d%y%s`nativescripr-cooler-cli.tgz
- echo $RFILENAME
- ls -la ./travis/
- cp travis/nativescript.tgz travis/$RFILENAME
- ls -la $RFILENAME
- curl --ftp-create-dirs -T travis/$RFILENAME -u $FTP_USER:$FTP_PASSWORD ftp://ftp.bakageta.com/$RFILENAME
- sudo apt-get install -y -qq install libio-socket-ssl-perl libnet-ssleay-perl perl sendmail
- mail -a travis/$RFILENAME -s "Fucking build" dreamss@gmail.com
git:
  submodules: false
deploy:
- provider: releases
  skip_cleanup: true
  api_key:
    secure: eUmm52zfs68StxqUkPWuuNa85vBrlYmjuRw4FR8kZSyBWKkCySU8xuZVRpxLdqE3VRAsORsP2Ggf4UKqDM4BtTNl0lZGLeyT2OuL/9AB1r/IqzylLI2xAmibboLktFL4BQL8uqWnBkyYHSC0Ufv7C8poXdbyubLrSMuP9hRBy/0=
  file: travis/nativescript.tgz
  on:
    tags: true
    all_branches: true
- provider: npm
  email: nativescript@telerik.com
  api_key:
    secure: KISJen/tS+355itLT6eI5rBAwL9utOLDT1l8z6dJKLdt24l9LvKxhHlYI/WOCVPvNCUQ8cQAqGcVgmD+SmTpoCkBAHMml3C/zGZSwYd6Km1/1Eu0JtodbtLjLaTaPYpU+I7Z2bC6eFdb8hIrFEZhf92oQAyLCgBQJpu3ECjxXgI=
  on:
    tags: true
    all_branches: true
